# Generated by Django 6.0.4 on 2026-05-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram_gb', models.FloatField()),
                ('tipo_ram', models.CharField(default='Desconocido', max_length=100)),
                ('storage_gb', models.FloatField()),
                ('tipo_disco', models.CharField(default='Desconocido', max_length=100)),
                ('install_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='api.zona')),
            ],
        ),
    ]
