# Generated by Django 6.0.4 on 2026-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram_gb', models.FloatField()),
                ('storage_gb', models.FloatField()),
                ('install_date', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Laboratorios de Informática', 'Laboratorios de Informática'), ('Oficinas VPDS', 'Oficinas VPDS')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
