# Generated by Django 6.0.4 on 2026-05-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='discos_detalle',
            field=models.JSONField(default=list),
        ),
    ]
