# Generated by Django 6.0.4 on 2026-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_computer_discos_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='alertas_remocion',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computer',
            name='hardware_extra',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='computer',
            name='programas',
            field=models.JSONField(default=list),
        ),
    ]
