# Generated by Django 6.0.4 on 2026-05-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computer_alertas_remocion_computer_hardware_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
