# Generated by Django 6.0.4 on 2026-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_computer_alias_computer_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='categoria',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorios'), ('VPDS', 'VPDS'), ('OTRO', 'Otras Áreas')], default='OTRO', max_length=20),
        ),
    ]
