# Generated by Django 6.0.4 on 2026-06-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='bios_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
